# Generated by Django 5.1.6 on 2026-09-24 03:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=4)),
                ('currency', models.CharField(max_length=8)),
                ('currency_symbol', models.CharField(blank=True, max_length=8)),
                ('is_european', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'destination countries',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('currency', models.CharField(max_length=8)),
                ('symbol', models.CharField(max_length=8)),
                ('ngn_per_unit', models.DecimalField(decimal_places=4, help_text='How many Naira one unit of this currency is worth.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
            ],
            options={
                'verbose_name_plural': 'origin countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=400)),
                ('badge', models.CharField(blank=True, default='Partner School', max_length=80)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('application_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged once per institution, never per course. 0 means fee-free.', max_digits=10)),
                ('tuition_summary', models.CharField(blank=True, max_length=200)),
                ('features', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='catalog.destinationcountry')),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('bachelors', "Bachelor's Degrees"), ('masters', 'Masters & MBA'), ('phd', 'PhD & Doctoral Programs'), ('diplomas', 'Diplomas & Certificates'), ('other', 'Other Academic Programs')], default='other', max_length=16)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('qualification_level', models.CharField(blank=True, help_text='e.g. Level 7 (RNCP41354)', max_length=80)),
                ('tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('intake', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('scholarship', models.CharField(blank=True, max_length=300)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='catalog.institution')),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_program_per_institution')],
            },
        ),
    ]
