# Generated by Django 5.1.6 on 2026-09-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ('display_order',), 'verbose_name': 'landing page question', 'verbose_name_plural': 'landing page questions'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('display_order', 'name'), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
