# Generated by Django 5.1.6 on 2026-09-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_faqitem_options_alter_program_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImport',
            fields=[
            ],
            options={
                'verbose_name': 'Add course',
                'verbose_name_plural': 'Add course',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.program',),
        ),
    ]
