# Generated by Django 5.1.6 on 2026-09-26 22:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_courseimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='tuition_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="A flat deposit in this school's currency, for schools that ask for a fixed sum rather than a share. Leave at 0 when a percentage is used.", max_digits=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='tuition_deposit_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Share of the total tuition taken as a deposit, e.g. 50 for half.', max_digits=5),
        ),
    ]
