# Generated by Django 5.1.6 on 2026-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_institution_tuition_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='application_fee_currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
    ]
