# Generated by Django 5.1.6 on 2026-09-30 04:52

import apps.applications.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_institution_application_fee_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="A wide photo of the campus. It is shown darkened behind the school's name.", null=True, upload_to=apps.applications.uploads.institution_cover_path),
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(blank=True, help_text='Where the campus is, as applicants should see it, e.g. Barcelona.', max_length=160),
        ),
    ]
