# Generated by Django 5.1.6 on 2026-09-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_institution_cover_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['country', 'is_active'], name='inst_country_active_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['display_order', 'name'], name='inst_order_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['institution', 'level'], name='prog_inst_level_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['level'], name='prog_level_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='prog_name_idx'),
        ),
    ]
