# Generated by Django 5.1.6 on 2026-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('agent', 'Partner agent'), ('supervisor', 'Sales manager'), ('staff', 'Admissions staff')], default='applicant', max_length=16),
        ),
    ]
