# Generated by Django 5.1.6 on 2026-09-29 11:50

import apps.applications.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.applications.uploads.avatar_upload_path),
        ),
    ]
