# Generated by Django 5.1.6 on 2026-09-29 11:55

import apps.accounts.models
import apps.applications.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.accounts.models._ticket_reference, editable=False, max_length=12, unique=True)),
                ('topic', models.CharField(choices=[('application', 'My application'), ('payment', 'Payment'), ('documents', 'Documents and letters'), ('account', 'Account and sign-in'), ('technical', 'Something is not working'), ('other', 'Something else')], default='other', max_length=16)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField(max_length=5000)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.applications.uploads.support_upload_path)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('emailed', models.BooleanField(default=False, help_text='Whether the message reached the support inbox.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'support message',
                'verbose_name_plural': 'support messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
