# Generated by Django 5.1.6 on 2026-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='Whether the person has confirmed this email address.'),
        ),
    ]
