# Generated by Django 5.1.6 on 2026-09-24 03:16

import apps.applications.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField(default=dict)),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(editable=False, max_length=16, unique=True)),
                ('field', models.CharField(max_length=60)),
                ('current_value', models.CharField(blank=True, max_length=250)),
                ('corrected_value', models.CharField(max_length=250)),
                ('reason', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='corrections/%Y/%m/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('declined', 'Declined')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('passport', 'International passport data page'), ('academic', 'Academic documents & transcripts'), ('cv', 'Curriculum vitae / resume'), ('other', 'Supporting document')], default='other', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=250)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending Review', 'Pending review'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending Review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('eta', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.applications.models.generate_reference, editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('previous_schools', models.CharField(blank=True, max_length=250)),
                ('qualification', models.CharField(blank=True, max_length=40)),
                ('year_graduated', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_gpa', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('admission_granted', 'Admitted'), ('rejected', 'Rejected')], default='submitted', max_length=24)),
                ('visa_status', models.CharField(choices=[('new', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Verified')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='catalog.destinationcountry')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='catalog.institution')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='catalog.origincountry')),
                ('programs', models.ManyToManyField(blank=True, related_name='applications', to='catalog.program')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
