# Generated by Django 5.1.6 on 2026-09-24 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted_by_agent',
            field=models.ForeignKey(blank=True, help_text='Set when a partner agent filed this application for the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='partners.agentprofile'),
        ),
        migrations.AddField(
            model_name='applicationdraft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='applications.application'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application'),
        ),
        migrations.AddField(
            model_name='stage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='applications.application'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['visa_status'], name='application_visa_st_360583_idx'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('application', 'order'), name='unique_stage_order'),
        ),
    ]
