# Generated by Django 5.1.6 on 2026-09-24 04:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offer', 'Offer letter'), ('admission', 'Admission letter'), ('acceptance', 'Confirmation of acceptance'), ('visa', 'Visa / study permit'), ('financial', 'Financial or scholarship letter'), ('other', 'Other correspondence')], default='offer', max_length=16)),
                ('title', models.CharField(help_text="What the applicant sees, e.g. 'Conditional offer'.", max_length=160)),
                ('file', models.FileField(upload_to='letters/%Y/%m/')),
                ('note', models.TextField(blank=True, help_text='Optional context shown beneath the title.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished letters are staged for review and stay hidden from the applicant.')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='applications.application')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
    ]
