# Generated by Django 5.1.6 on 2026-09-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'correction request', 'verbose_name_plural': 'correction requests'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('uploaded_at',), 'verbose_name': 'applicant document', 'verbose_name_plural': 'applicant documents'},
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ('-issued_at',), 'verbose_name': 'issued letter', 'verbose_name_plural': 'issued letters'},
        ),
    ]
