# Generated by Django 5.1.6 on 2026-09-24 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_correctionrequest_options_and_more'),
        ('catalog', '0001_initial'),
        ('partners', '0007_alter_agentprofile_options_alter_loan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaSupportApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Visa Support Queue (Admitted Student)',
                'verbose_name_plural': 'Visa Support Queue (Admitted Students)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.AddField(
            model_name='application',
            name='transferred_to_visa_support',
            field=models.BooleanField(default=False, help_text='Transferred to Visa Support Assistant for student visa processing.'),
        ),
        migrations.AddField(
            model_name='application',
            name='transferred_to_visa_support_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the file was transferred to Visa Support.', null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['transferred_to_visa_support'], name='application_transfe_696b5e_idx'),
        ),
    ]
