# Generated by Django 5.1.6 on 2026-09-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_visasupportapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=True, help_text='Turned off for the entries written while an application is being submitted. Those all happen within a few seconds of the welcome email, and mailing each one would mean half a dozen messages for a single sign-up.'),
        ),
    ]
