# Generated by Django 5.1.6 on 2026-09-25 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_notification_send_email'),
        ('catalog', '0003_courseimport'),
        ('partners', '0007_alter_agentprofile_options_alter_loan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='academic_details_verified',
            field=models.BooleanField(default=False, help_text='Prior academic records, institution, and major choice verified.'),
        ),
        migrations.AddField(
            model_name='application',
            name='documents_verified',
            field=models.BooleanField(default=False, help_text='All submitted supporting documents verified by admissions staff.'),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Application fee and tuition payment clearance confirmed.'),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_details_verified',
            field=models.BooleanField(default=False, help_text='Personal profile and contact info verified by admissions staff.'),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admissions desk remarks or instructions regarding applicant verification.'),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('in_review', 'In Review'), ('verified', 'Verified'), ('action_required', 'Action Required')], default='unverified', help_text='Admissions desk verification and compliance status.', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when verification was completed.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who conducted the verification audit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['verification_status'], name='application_verific_d43e6d_idx'),
        ),
    ]
