# Generated by Django 5.1.6 on 2026-09-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_academic_details_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_course_name',
            field=models.CharField(blank=True, default='', help_text='The course / program title typed directly by the applicant.', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='is_custom_course',
            field=models.BooleanField(default=False, help_text='True if applicant entered their desired course manually instead of picking from catalog.'),
        ),
    ]
