# Generated by Django 5.1.6 on 2026-09-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_custom_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='initial_password',
            field=models.CharField(blank=True, default='', help_text='Temporary password generated during application to be emailed upon successful payment settlement.', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the applicant welcome email with credentials has been dispatched.'),
        ),
    ]
