# Generated by Django 5.1.6 on 2026-09-29 11:50

import apps.applications.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_initial_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionrequest',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=apps.applications.uploads.correction_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.applications.uploads.document_upload_path),
        ),
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.FileField(upload_to=apps.applications.uploads.letter_upload_path),
        ),
    ]
