# Generated by Django 5.1.6 on 2026-09-30 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_correctionrequest_evidence_alter_document_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='correctionrequest',
            index=models.Index(fields=['status'], name='corr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application', 'uploaded_at'], name='doc_app_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['application', 'is_published'], name='letter_app_published_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['application', '-created_at'], name='notif_app_created_idx'),
        ),
    ]
