# Generated by Django 5.1.6 on 2026-09-30 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_search_indexes'),
        ('catalog', '0007_search_indexes'),
        ('partners', '0008_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-submitted_at'], name='app_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='app_email_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_by_agent', '-submitted_at'], name='app_agent_submitted_idx'),
        ),
    ]
