# Generated by Django 5.1.6 on 2026-09-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_document_review'),
        ('partners', '0009_studentdraft_studentdraftfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
            ],
            options={
                'verbose_name': 'agent-filed application',
                'verbose_name_plural': 'agent-filed applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='AgentApplications',
            fields=[
            ],
            options={
                'verbose_name': 'agent applications',
                'verbose_name_plural': 'agent applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('partners.agentprofile',),
        ),
    ]
