# Generated by Django 5.1.6 on 2026-09-30 14:02

import apps.applications.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_two_verification_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraftFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=24)),
                ('kind', models.CharField(default='other', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to=apps.applications.uploads.draft_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.applicationdraft')),
            ],
            options={
                'ordering': ('uploaded_at',),
                'constraints': [models.UniqueConstraint(fields=('draft', 'slot'), name='one_file_per_application_draft_slot')],
            },
        ),
    ]
