# Generated by Django 5.1.6 on 2026-09-24 06:35

import apps.partners.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_letter'),
        ('partners', '0002_registration_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(default=apps.partners.models.generate_agent_code, help_text='Agents enter this when they register to join this supervisor.', max_length=12, unique=True)),
                ('region', models.CharField(blank=True, help_text='Territory or team this supervisor covers.', max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Turning this off stops the code being accepted by new agents.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Set from the agent code entered at sign-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='partners.supervisorprofile'),
        ),
        migrations.CreateModel(
            name='SupervisorBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=10)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text='The agent whose student earned it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_bonuses', to='partners.agentprofile')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_bonuses', to='applications.application')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='partners.supervisorprofile')),
            ],
            options={
                'verbose_name_plural': 'supervisor bonuses',
                'ordering': ('-earned_at',),
                'constraints': [models.UniqueConstraint(fields=('application',), name='one_supervisor_bonus_per_application')],
            },
        ),
    ]
