# Generated by Django 5.1.6 on 2026-09-24 12:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_sales_manager_code_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='The sales manager whose code this agent used at sign-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='partners.supervisorprofile'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ad_account_link',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='supervisorbonus',
            name='agent',
            field=models.ForeignKey(help_text='The agent who registered the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_bonuses', to='partners.agentprofile'),
        ),
        migrations.AlterField(
            model_name='supervisorbonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('3000'), max_digits=10),
        ),
        migrations.CreateModel(
            name='SupervisorWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'In review'), ('completed', 'Paid out'), ('rejected', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='partners.supervisorprofile')),
            ],
            options={
                'verbose_name': 'sales manager payout',
                'verbose_name_plural': 'sales manager payouts',
                'ordering': ('-created_at',),
            },
        ),
    ]
