# Generated by Django 5.1.6 on 2026-09-24 14:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_agentprofile_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorbonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=10),
        ),
    ]
