# Generated by Django 5.1.6 on 2026-09-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_supervisorbonus_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('-requested_at',), 'verbose_name': 'ad funding request', 'verbose_name_plural': 'ad funding requests'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ('-created_at',), 'verbose_name': 'agent payout', 'verbose_name_plural': 'agent payouts'},
        ),
    ]
