# Generated by Django 5.1.6 on 2026-09-30 11:30

import apps.applications.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='partners.agentprofile')),
            ],
            options={
                'verbose_name': 'student draft',
                'verbose_name_plural': 'student drafts',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentDraftFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=24)),
                ('kind', models.CharField(default='other', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to=apps.applications.uploads.draft_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='partners.studentdraft')),
            ],
            options={
                'ordering': ('uploaded_at',),
                'constraints': [models.UniqueConstraint(fields=('draft', 'slot'), name='one_file_per_draft_slot')],
            },
        ),
    ]
