# Generated by Django 5.1.6 on 2026-09-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_studentdraft_studentdraftfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('-requested_at',), 'verbose_name': 'ads funding request', 'verbose_name_plural': 'ads funding requests'},
        ),
    ]
