# Generated by Django 5.1.6 on 2026-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_alter_loan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorwithdrawal',
            name='paid_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paid_to',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
