# Generated by Django 5.1.6 on 2026-10-01 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_withdrawal_paid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='loan_repaid_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
