# Generated by Django 5.1.6 on 2026-10-06 14:17

from decimal import Decimal

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Commissions so far were all paid in Naira: record that. A wallet with
    no money in it yet takes the currency of its agent's country, so an agent
    outside Nigeria is shown their own currency from their first commission."""
    Commission = apps.get_model("partners", "Commission")
    Wallet = apps.get_model("partners", "Wallet")
    OriginCountry = apps.get_model("catalog", "OriginCountry")

    for commission in Commission.objects.all():
        Commission.objects.filter(pk=commission.pk).update(
            currency="NGN", amount_ngn=commission.amount, fx_rate=Decimal("1")
        )

    zero = Decimal("0.00")
    for wallet in Wallet.objects.select_related("agent__user"):
        amounts = (
            wallet.total_earned, wallet.loan_balance, wallet.saved_balance,
            wallet.total_withdrawn, wallet.loan_repaid_total,
        )
        if any(value != zero for value in amounts):
            continue  # money already in Naira stays in Naira
        country = (wallet.agent.user.country or "").strip()
        row = OriginCountry.objects.filter(name__iexact=country).first() if country else None
        currency = (row.currency or "NGN").strip().upper() if row else "NGN"
        Wallet.objects.filter(pk=wallet.pk).update(currency=currency)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_african_currencies"),
        ('partners', '0013_loanrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='amount_ngn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='commission',
            name='currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
        migrations.AddField(
            model_name='commission',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
]
