# Generated by Django 5.1.6 on 2026-09-24 03:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('gateway', models.CharField(choices=[('Paystack', 'Paystack'), ('Flutterwave', 'Flutterwave'), ('Institutional Waiver', 'Institutional waiver'), ('Agent Payout / Verified Partner', 'Partner payout')], default='Paystack', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Paid', 'Paid'), ('waived', 'Waived (partner)'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('symbol', models.CharField(default='₦', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fx_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.application')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
