# Generated by Django 5.1.6 on 2026-09-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',), 'verbose_name': 'application fee', 'verbose_name_plural': 'application fees'},
        ),
    ]
