# Generated by Django 5.1.6 on 2026-09-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_search_indexes'),
        ('payments', '0004_payment_gateway_reference_payment_processing_fee_ngn_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
    ]
