# Generated by Django 5.1.6 on 2026-09-30 11:30

import apps.applications.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToConfirm',
            fields=[
            ],
            options={
                'verbose_name': 'payment to confirm',
                'verbose_name_plural': 'payments to confirm',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.applications.uploads.receipt_upload_path),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Flutterwave', 'Flutterwave'), ('Bank transfer', 'Bank transfer'), ('Institutional Waiver', 'Institutional waiver'), ('Agent Payout / Verified Partner', 'Partner payout')], default='Paystack', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Awaiting confirmation'), ('paid', 'Paid'), ('waived', 'Waived (partner)'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
    ]
