# Generated by Django 5.1.6 on 2026-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymenttoconfirm_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transfer_bank',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
