/**
 * Embedded partner institutions and course catalogue.
 * Guaranteed to be available instantly in the frontend even if backend is waking up.
 */

export const DEFAULT_CATALOG = [
  {
    "id": 8,
    "slug": "insa-business-school",
    "name": "INSA Business School",
    "country": "Spain",
    "location": "Barcelona, Spain",
    "tagline": "Business, marketing and technology masters",
    "badge": "Partner School",
    "currency": "EUR",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "50.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "50% of total tuition as a deposit",
    "tuition_summary": "\u20ac4,900 - \u20ac11,900 / year",
    "features": [],
    "programs": [
      {
        "id": 212,
        "name": "Bachelor's Degree in International Business",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "7500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 213,
        "name": "Bachelor's Degree in Business and Marketing",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "7500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 214,
        "name": "Master in Artificial Intelligence, Data and Cloud",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 215,
        "name": "Master in International Business Communication",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 216,
        "name": "Lifelong Learning Master in Business Event Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 217,
        "name": "International MBA",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 218,
        "name": "Master in Digital Marketing and Customer Experience",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 219,
        "name": "Master in Business Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 220,
        "name": "Master in Project Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 221,
        "name": "Master in Business Administration",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 222,
        "name": "Master in Integral Logistics Operations and Supply Chain Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 223,
        "name": "Master in Business Communication",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7400.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 224,
        "name": "Master in Marketing Digital y Social Media",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 225,
        "name": "Master in Marketing Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 226,
        "name": "Master in Entrepreneurship and Innovation",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 227,
        "name": "Master in Big Data and Data Intelligence",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 228,
        "name": "Master in Foreign Trade and International Marketing",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 229,
        "name": "Master in Business Sustainability Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 230,
        "name": "Master in Digital Business Transformation",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 231,
        "name": "Master in Data Visualization Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 232,
        "name": "Master in Logistics",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 9,
    "slug": "c3s-business-school",
    "name": "C3S Business School",
    "country": "Spain",
    "location": "Barcelona, Spain",
    "tagline": "OTHM and NCC accredited diplomas, degrees and masters",
    "badge": "Partner School",
    "currency": "EUR",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "50.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "50% of total tuition as a deposit",
    "tuition_summary": "\u20ac7,000 - \u20ac11,000 / year",
    "features": [],
    "programs": [
      {
        "id": 233,
        "name": "OTHM Level 5 Diploma in Business Management",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7000.00",
        "intake": "October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 234,
        "name": "Diploma in Hospitality Management",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7000.00",
        "intake": "October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 235,
        "name": "Diploma in Information Technology",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7000.00",
        "intake": "October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 236,
        "name": "BA (Hons) in Management",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 237,
        "name": "BA (Hons) in Business Analytics and Digital Transformation",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 238,
        "name": "BA (Hons) in Business Management (Finance and Tech Compliance)",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 239,
        "name": "BA (Hons) in Business Management (Entrepreneurship)",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 240,
        "name": "BA (Hons) in Business Management (International Business and Cross-Border Trade)",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 241,
        "name": "BA (Hons) in Business Computing & Information Systems (NCC)",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 242,
        "name": "BA (Hons) in Tourism",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 243,
        "name": "Global MBA",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11000.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 244,
        "name": "Master in Business Analytics & Data Science for Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11000.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 245,
        "name": "Master in Entrepreneurship & Business Transformation",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11000.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 246,
        "name": "Master in Project Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11000.00",
        "intake": "February, May & October",
        "note": "",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 10,
    "slug": "ucam-universidad",
    "name": "UCAM Universidad Cat\u00f3lica de Murcia",
    "country": "Spain",
    "location": "Murcia, Spain",
    "tagline": "One of Spain's most innovative private universities, with degrees across medicine, sport, law and technology",
    "badge": "Partner University",
    "currency": "EUR",
    "application_fee_currency": "EUR",
    "application_fee": "150.00",
    "application_fee_ngn": "252000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "50.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "50% of total tuition as a deposit",
    "tuition_summary": "\u20ac1,300 - \u20ac15,200 / year",
    "features": [],
    "programs": [
      {
        "id": 247,
        "name": "Bachelor in Business Administration and Management",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6750.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 248,
        "name": "Bachelor in Biotechnology",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "8100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 249,
        "name": "Bachelor in Business Administration",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 250,
        "name": "Bachelor in Physical Activity & Sport",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 251,
        "name": "Bachelor in Criminology",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "4990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 252,
        "name": "Bachelor in Dance",
        "level": "bachelors",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "5000.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 253,
        "name": "Bachelor's Degree in Dentistry",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "15200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 254,
        "name": "Degree in Law",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 255,
        "name": "Degree in Early Childhood Education",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 256,
        "name": "Bachelor's in Advertising and Public Relations",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 257,
        "name": "Bachelor's Degree in Audiovisual Communication",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 258,
        "name": "Bachelor's Degree in Journalism",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 259,
        "name": "Bachelor's Degree in Advertising, Public Relations & Content Marketing",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 260,
        "name": "Bachelor's Degree in Marketing & Commercial Management",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 261,
        "name": "Bachelor's Degree in Tourism",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 262,
        "name": "Bachelor's Degree in Psychology",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "7950.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 263,
        "name": "Bachelor's Degree in Primary Education",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 264,
        "name": "Bachelor's Degree in Translation & Interpretation",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 265,
        "name": "Bachelor's Degree in Medicine",
        "level": "bachelors",
        "duration": "6 years",
        "qualification_level": "",
        "tuition": "15150.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 266,
        "name": "Bachelor's Degree in Nursing",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "10500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 267,
        "name": "Bachelor's Degree in Food Science & Technology",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5400.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 268,
        "name": "Bachelor's Degree in Gastronomy",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6450.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 269,
        "name": "Bachelor's Degree in Human Nutrition and Dietetics",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 270,
        "name": "Bachelor's Degree in Pharmacy",
        "level": "bachelors",
        "duration": "5 years",
        "qualification_level": "",
        "tuition": "9450.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 271,
        "name": "Bachelor's Degree in Physiotherapy",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "10000.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 272,
        "name": "Bachelor's Degree in Fundamentals of Architecture",
        "level": "bachelors",
        "duration": "5 years",
        "qualification_level": "",
        "tuition": "6200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 273,
        "name": "Degree in Civil Engineering",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 274,
        "name": "Degree in Computer Engineering",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 275,
        "name": "Degree in Building Engineering (Technical Architecture, Spanish)",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 276,
        "name": "Degree in Telecommunications Engineering (Spanish)",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5550.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 277,
        "name": "Bachelor's Degree in International Relations",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 278,
        "name": "Degree in End-of-Life Care",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 279,
        "name": "Degree in Marketing & Sales Management",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 280,
        "name": "Degree in Medicine",
        "level": "bachelors",
        "duration": "5 years",
        "qualification_level": "",
        "tuition": "15150.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 281,
        "name": "Degree in Human Nutrition & Dietetics (Spanish)",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "6600.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 282,
        "name": "Degree in Dentistry",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "14500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 283,
        "name": "Degree in Journalism",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 284,
        "name": "Bachelor's Degree in Sport and Exercise Sciences",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "7800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 285,
        "name": "Degree in Chiropody",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "7900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 286,
        "name": "Degree in Occupational Therapy",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 287,
        "name": "Degree in Translation and Interpretation (Spanish)",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "5900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 288,
        "name": "Degree in Tourism and Management of Tourism Business (Spanish)",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "4250.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 289,
        "name": "Bachelor's Degree in Veterinary Medicine",
        "level": "bachelors",
        "duration": "5 years",
        "qualification_level": "",
        "tuition": "12990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 290,
        "name": "Master's Degree in Access to the Professions of Lawyer and Solicitor (Spanish)",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "4500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 291,
        "name": "Master's Degree in Architecture (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4850.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 292,
        "name": "Master's Degree in Audiology and Balance (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 293,
        "name": "Master's Degree in Bilingual Education (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 294,
        "name": "Master's Degree in Business Administration, MBA (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "10200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 295,
        "name": "Master's Degree in Foot Surgery for Podiatrists (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "9500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 296,
        "name": "Master's Degree in Development, Management and Sustainable Tourism Policy (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 297,
        "name": "Master's Degree in Development, Management and Sustainable Tourism Policy",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 298,
        "name": "Master's Degree in Management and Administration of Sports Entities (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 299,
        "name": "Master's Degree in Emergency, Urgent Care and Special Care Nursing (Spanish)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6750.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 300,
        "name": "Master's Degree in School Nursing and Health",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 301,
        "name": "Master's Degree in High Performance Sports: Strength and Physical Conditioning",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 302,
        "name": "Master's Degree in Architecture",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4850.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 303,
        "name": "Master's Degree in Audiology and Balance",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "4850.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 304,
        "name": "Master's Degree in Management and Administration of Sports Entities",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 305,
        "name": "Master's Degree in Physical Exercise and Training for Health",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 306,
        "name": "Master's Degree in Bilingual Education: English (CLIL)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 307,
        "name": "Master's Degree in Physiotherapy in Sport",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 308,
        "name": "Master's Degree in Teacher Training",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7050.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 309,
        "name": "Master's Degree in Geriatrics and Gerontology: Comprehensive Care for Dependency",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 310,
        "name": "Master's Degree in Management and Planning of Health Services",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7300.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 311,
        "name": "Master's Degree in High Performance Sport: Strength and Conditioning",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "9300.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 312,
        "name": "Master's Degree in Hospitality Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7600.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 313,
        "name": "Master's Degree in Civil Engineering",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "5700.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 314,
        "name": "Master's Degree in Innovation and Tourism Marketing",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 315,
        "name": "Master's Degree in Research in Physical Education and Health",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "5200.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 316,
        "name": "Master's Degree in Management of Sport Entities",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11700.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 317,
        "name": "Master's Degree in Marketing and Communication",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 318,
        "name": "Master's Degree in Emergency Medicine",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7000.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 319,
        "name": "Master's Degree in Clinical Nutrition",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "6500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 320,
        "name": "Master's Degree in Nutrition in Physical Activity and Sport (Blended Learning)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7300.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 321,
        "name": "Master's Degree in Nutrition and Food Security (Blended Learning)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 322,
        "name": "Master's Degree in Osteopathy and Manual Therapy (Blended Learning)",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "11950.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 323,
        "name": "Master's Degree in General Health Psychology",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "14100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 324,
        "name": "Master's Degree in Corporate Social Responsibility",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4350.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 325,
        "name": "Master's Degree in Voice, Language and Communication Disorders",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4150.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 326,
        "name": "Master's Degree in Continuing Education Composition for VFX (Blended Learning)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 327,
        "name": "Master's Degree in International Relations",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 328,
        "name": "Master's Degree in MBA in Sports Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "8980.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 329,
        "name": "Master's Degree in Continuing Education Digital Marketing & Strategy (Blended Learning)",
        "level": "masters",
        "duration": "9 months",
        "qualification_level": "",
        "tuition": "4000.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 330,
        "name": "Master's Degree in Continuing Education BIM/GIS Methodology, Programming & Data Governance (Blended Learning)",
        "level": "masters",
        "duration": "9 months",
        "qualification_level": "",
        "tuition": "3800.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 331,
        "name": "Master's Degree in Clinical and Sports Podiatry (Blended Learning)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4600.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 332,
        "name": "Master's Degree in Physical Preparation and Sports Rehabilitation in Football",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "7990.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 333,
        "name": "Master's Degree in Continuing Education Music Production",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "3900.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 334,
        "name": "Master's Degree in MBA Sport Management",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "11700.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 335,
        "name": "Master's Degree in Continuing Education Digital Transformation of the Agriculture Sector (Blended Learning)",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "4300.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 336,
        "name": "Master's Degree in Continuing Education Sport Traumatology",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "8500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 337,
        "name": "Master's Degree in Continuing Education Graphic Design On/Offline",
        "level": "masters",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "5500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 338,
        "name": "Master's Degree in Corporate Tax Consulting",
        "level": "masters",
        "duration": "9 months",
        "qualification_level": "",
        "tuition": "4500.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 339,
        "name": "Master's Degree in Big Data & Data Engineering",
        "level": "masters",
        "duration": "9 months",
        "qualification_level": "",
        "tuition": "4100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 340,
        "name": "Executive Master in Financial Management",
        "level": "masters",
        "duration": "9 months",
        "qualification_level": "",
        "tuition": "4100.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 341,
        "name": "PhD in Social Sciences",
        "level": "phd",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "1800.00",
        "intake": "",
        "note": "\u20ac1,800 per year",
        "scholarship": ""
      },
      {
        "id": 342,
        "name": "PhD in Health Sciences",
        "level": "phd",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "1300.00",
        "intake": "",
        "note": "\u20ac1,300 per year",
        "scholarship": ""
      },
      {
        "id": 343,
        "name": "PhD in Sports Sciences",
        "level": "phd",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "1300.00",
        "intake": "",
        "note": "\u20ac1,300 per year",
        "scholarship": ""
      },
      {
        "id": 344,
        "name": "PhD in Computer Technologies and Environmental Engineering",
        "level": "phd",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "1300.00",
        "intake": "",
        "note": "\u20ac1,300 per year",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 11,
    "slug": "paris-business-academy",
    "name": "Paris Business Academy (PBA)",
    "country": "France",
    "location": "Paris, France",
    "tagline": "State-recognised RNCP Level 6 and 7 degrees in business and digital",
    "badge": "Premier Partner",
    "currency": "EUR",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "0.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "",
    "tuition_summary": "\u20ac7,500 - \u20ac12,000 first year",
    "features": [],
    "programs": [
      {
        "id": 345,
        "name": "Bachelor's in Web Marketing",
        "level": "bachelors",
        "duration": "3 Years",
        "qualification_level": "Level 6 (RNCP35634)",
        "tuition": "10000.00",
        "intake": "September / October & January",
        "note": "\u20ac10,000 per year + \u20ac690 other expenses",
        "scholarship": "25% scholarship: \u20ac7,500/yr + \u20ac690 other expenses"
      },
      {
        "id": 346,
        "name": "Bachelor's in Digital Project Management",
        "level": "bachelors",
        "duration": "3 Years",
        "qualification_level": "Level 6 (RNCP35634)",
        "tuition": "10000.00",
        "intake": "September / October & January",
        "note": "\u20ac10,000 per year + \u20ac690 other expenses",
        "scholarship": "25% scholarship: \u20ac7,500/yr + \u20ac690 other expenses"
      },
      {
        "id": 347,
        "name": "Bachelor's in Web Development",
        "level": "bachelors",
        "duration": "3 Years",
        "qualification_level": "Level 6 (RNCP35634)",
        "tuition": "10000.00",
        "intake": "September / October & January",
        "note": "\u20ac10,000 per year + \u20ac690 other expenses",
        "scholarship": "25% scholarship: \u20ac7,500/yr + \u20ac690 other expenses"
      },
      {
        "id": 348,
        "name": "Global MBA",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP41354)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": "25% scholarship: \u20ac9,000 + \u20ac690 other expenses"
      },
      {
        "id": 349,
        "name": "Mast\u00e8re in Business Project Management",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP41354)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": "25% scholarship: \u20ac9,000 + \u20ac690 other expenses"
      }
    ]
  },
  {
    "id": 12,
    "slug": "financia-business-school",
    "name": "Financia Business School",
    "country": "France",
    "location": "Paris, France",
    "tagline": "Specialist finance and management school with RNCP accredited degrees and MBAs",
    "badge": "Finance Specialist",
    "currency": "EUR",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "0.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "",
    "tuition_summary": "\u20ac10,000 - \u20ac12,000 first year",
    "features": [],
    "programs": [
      {
        "id": 350,
        "name": "Bachelor in Business Development",
        "level": "bachelors",
        "duration": "3 Years",
        "qualification_level": "Level 6 (RNCP40889, Formatives)",
        "tuition": "10000.00",
        "intake": "September / October & January",
        "note": "\u20ac10,000 per year + \u20ac690 other expenses",
        "scholarship": ""
      },
      {
        "id": 351,
        "name": "MBA Corporate Finance & Financial Control",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP41469)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": ""
      },
      {
        "id": 352,
        "name": "MBA Trading & Finance",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP38601)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 13,
    "slug": "alternis-business-school",
    "name": "Alternis Business School",
    "country": "France",
    "location": "Paris, France",
    "tagline": "Work-study and management excellence, RNCP Level 6 and 7 certified",
    "badge": "Partner School",
    "currency": "EUR",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "0.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "",
    "tuition_summary": "\u20ac10,000 - \u20ac12,000 first year",
    "features": [],
    "programs": [
      {
        "id": 353,
        "name": "Bachelor in Business Development",
        "level": "bachelors",
        "duration": "3 Years",
        "qualification_level": "Level 6 (RNCP40889, Formatives)",
        "tuition": "10000.00",
        "intake": "September / October & January",
        "note": "\u20ac10,000 per year + \u20ac690 other expenses",
        "scholarship": ""
      },
      {
        "id": 354,
        "name": "MBA Logistics, Purchasing and Supply Chain",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP37618, ESLI)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 14,
    "slug": "hema-groupe",
    "name": "HEMA Groupe",
    "country": "France",
    "location": "Paris, France",
    "tagline": "A group of specialist schools: ESMA, ISEADD and ISEAM",
    "badge": "Partner School",
    "currency": "EUR",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "0.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "",
    "tuition_summary": "\u20ac10,000 - \u20ac12,000 first year",
    "features": [],
    "programs": [
      {
        "id": 355,
        "name": "Bachelor's in Manager of Business Development (ESMA School)",
        "level": "bachelors",
        "duration": "3 Years",
        "qualification_level": "Level 6 (RNCP38602)",
        "tuition": "10000.00",
        "intake": "September / October & January",
        "note": "\u20ac10,000 per year + \u20ac690 other expenses",
        "scholarship": ""
      },
      {
        "id": 356,
        "name": "Mast\u00e8re in Sustainable Development & CSR (ISEADD School)",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP40654)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": ""
      },
      {
        "id": 357,
        "name": "Mast\u00e8re in Energy, Environment and Climate Management (ISEADD School)",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP40655)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": ""
      },
      {
        "id": 358,
        "name": "Mast\u00e8re in Innovative Project Management (ISEAM School)",
        "level": "masters",
        "duration": "2 Years",
        "qualification_level": "Level 7 (RNCP41354)",
        "tuition": "12000.00",
        "intake": "September / October & January",
        "note": "Total \u20ac18,000. First year \u20ac12,000 + \u20ac690 other expenses",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 15,
    "slug": "sheridan-college",
    "name": "Sheridan College",
    "country": "Canada",
    "location": "Ontario, Canada",
    "tagline": "Degrees, diplomas and graduate certificates across animation, health, engineering and business",
    "badge": "Partner College",
    "currency": "CAD",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "50.00",
    "tuition_deposit_amount": "0.00",
    "deposit_note": "50% of total tuition as a deposit",
    "tuition_summary": "C$16,954 - C$39,045 / year",
    "features": [],
    "programs": [
      {
        "id": 359,
        "name": "Bachelor in Nursing",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "26576.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 360,
        "name": "Bachelor of Osteopathy",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "23099.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 361,
        "name": "Bachelor of Textiles, Craft and Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21255.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 362,
        "name": "Bachelor in 3D Animation and Emerging Technologies",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "31227.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 363,
        "name": "Bachelor of Animation, Honours",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "10353.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 364,
        "name": "Bachelor of Art and Art History",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 365,
        "name": "Bachelor of Athletic Therapy, Health Sciences",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "29108.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 366,
        "name": "Bachelor in Ceramics, Craft and Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21255.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 367,
        "name": "Bachelor in Computer Science, Mobile Computing",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21472.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 368,
        "name": "Bachelor of Computer Science",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "23011.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 369,
        "name": "Bachelor in Cyber Security, Information Sciences",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "23824.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 370,
        "name": "Bachelor in Electrical Engineering",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "23452.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 371,
        "name": "Bachelor in Experiential Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "23960.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 372,
        "name": "Bachelor of Film and Television",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "29659.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 373,
        "name": "Bachelor of Furniture, Craft and Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21255.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 374,
        "name": "Bachelor of Game Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "22576.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 375,
        "name": "Bachelor in Glass, Craft and Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21255.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 376,
        "name": "Bachelor in Illustration",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 377,
        "name": "Bachelor in Industrial Design, Craft and Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21255.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 378,
        "name": "Bachelor in Interaction Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "22424.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 379,
        "name": "Bachelor of Interior Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "24887.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 380,
        "name": "Bachelor in Kinesiology and Health Promotion, Health Sciences",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "28854.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 381,
        "name": "Bachelor in Music Theatre Performance",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "39045.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 382,
        "name": "Bachelor in Mechanical Engineering",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "23243.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 383,
        "name": "Bachelor in Multidisciplinary, Craft and Design",
        "level": "bachelors",
        "duration": "4 years",
        "qualification_level": "",
        "tuition": "21255.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 384,
        "name": "Honours Bachelor of Early Childhood Leadership",
        "level": "bachelors",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "24271.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 385,
        "name": "Master of Animation, Games and Immersive Experiences",
        "level": "masters",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "32347.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 386,
        "name": "Diploma in Computer Systems Technician, Cyber Security",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19701.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 387,
        "name": "Diploma in Educational Support",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19901.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 388,
        "name": "Diploma in Electrical Engineering Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20329.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 389,
        "name": "Diploma in Computer Systems Technician, Information Technology Infrastructure and Services",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19701.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 390,
        "name": "Diploma in Graphic Design, Creative Practice",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "18756.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 391,
        "name": "Diploma in Accounting, Business",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "16956.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 392,
        "name": "Diploma in Business",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "16954.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 393,
        "name": "Diploma in Addictions and Mental Health",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19410.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 394,
        "name": "Diploma in CNC & Precision Machining, Mechanical Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20587.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 395,
        "name": "Diploma in Advertising and Marketing Communications",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19739.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 396,
        "name": "Diploma in Computer Engineering Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20364.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 397,
        "name": "Diploma in Computer Programming",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19701.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 398,
        "name": "Diploma in Architectural Technician, Sustainable Design",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20019.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 399,
        "name": "Diploma in Construction Engineering Technician, Sustainability",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "21914.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 400,
        "name": "Diploma in General Arts & Science",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19671.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 401,
        "name": "Diploma in Industrial Millwright, Mechanical Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "21684.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 402,
        "name": "Diploma in Interior Decorating",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19859.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 403,
        "name": "Diploma in Makeup for Media and Creative Arts",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "21360.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 404,
        "name": "Diploma in Marketing, Business",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "16954.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 405,
        "name": "Diploma in Early Childhood Education",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19721.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 406,
        "name": "Diploma in Early Childhood Education, Intensive",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "19651.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 407,
        "name": "Diploma in Nutrition and Food Service Management",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19731.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 408,
        "name": "Diploma in Office Administration, Health Services",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19787.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 409,
        "name": "Diploma in Pharmacy Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19779.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 410,
        "name": "Diploma in Plumbing Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20412.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 411,
        "name": "Diploma in Police Foundations",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19823.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 412,
        "name": "Diploma in Practical Nursing",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "25793.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 413,
        "name": "Diploma in Social Service Worker",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19786.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 414,
        "name": "Diploma in Social Service Worker, Gerontology",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19886.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 415,
        "name": "Diploma in Welding and Fabrication Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20383.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 416,
        "name": "Diploma in Visual and Creative Arts",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20535.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 417,
        "name": "Diploma in Veterinary Technician",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "21205.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 418,
        "name": "Advanced Diploma in Technical Production for the Performing Arts Industry",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "21536.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 419,
        "name": "Advanced Diploma in Network Engineering Technology",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "19774.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 420,
        "name": "Advanced Diploma in Diagnostic Imaging Technology",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "21084.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 421,
        "name": "Advanced Diploma in Graphic Design, Creative Strategies",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "18756.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 422,
        "name": "Advanced Diploma in Computer Systems Technology, Analysis and Design",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "20019.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 423,
        "name": "Advanced Diploma in Computer Systems Technology, Software Development and Network Engineering",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "19701.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 424,
        "name": "Advanced Diploma in Child and Youth Care",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "19769.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 425,
        "name": "Advanced Diploma in Advertising and Marketing Communications, Management",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "19739.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 426,
        "name": "Advanced Diploma in Architectural Technology, Sustainable Design",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "20019.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 427,
        "name": "Advanced Diploma in Marketing, Business Administration",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "16954.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 428,
        "name": "Advanced Diploma in Massage Therapy",
        "level": "diplomas",
        "duration": "3 years",
        "qualification_level": "",
        "tuition": "18989.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 429,
        "name": "Graduate Certificate in Artificial Intelligence Development and Applications",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "20670.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 430,
        "name": "Graduate Certificate in Marketing Management, Digital Strategies",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "16442.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 431,
        "name": "Graduate Certificate in Internet of Things and Machine Intelligence",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "18766.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 432,
        "name": "Graduate Certificate in Interactive Media Management, Digital Design",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "25729.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 433,
        "name": "Graduate Certificate in Music Scoring for Screen and Stage",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "33769.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 434,
        "name": "Graduate Certificate in Game Development, Advanced Programming",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "27928.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 435,
        "name": "Graduate Certificate in Digital Product Design",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "27745.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 436,
        "name": "Graduate Certificate in Financial Technology",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20057.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 437,
        "name": "Graduate Certificate in Clinical Kinesiology",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "18831.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 438,
        "name": "Graduate Certificate in Healthcare Administration and Service Management",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "21483.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 439,
        "name": "Graduate Certificate in Computer Animation",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "26641.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 440,
        "name": "Graduate Certificate in Advanced Special Effects Makeup, Prosthetics and Props",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "27319.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 441,
        "name": "Graduate Certificate in Advanced Television and Film",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "34246.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 442,
        "name": "Graduate Certificate in Applied Data Analytics and Visualization",
        "level": "diplomas",
        "duration": "2 years",
        "qualification_level": "",
        "tuition": "19766.00",
        "intake": "",
        "note": "Tuition to be confirmed with the college",
        "scholarship": ""
      },
      {
        "id": 443,
        "name": "Graduate Certificate in Human Resources Management",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "21655.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 444,
        "name": "Graduate Certificate in Operational Technology Cybersecurity",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "19943.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 445,
        "name": "Graduate Certificate in Project Management, Information Technology",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "19814.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 446,
        "name": "Graduate Certificate in Supply Chain Management, Logistics Automation",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "18541.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 447,
        "name": "Graduate Certificate in Urban Design",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "18639.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 448,
        "name": "Graduate Certificate in Visual Effects",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "26641.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 449,
        "name": "Certificate in Welding Techniques",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20383.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 450,
        "name": "Certificate in Personal Support Worker",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20933.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 451,
        "name": "Certificate in Plumbing, Mechanical Techniques",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20412.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 452,
        "name": "Certificate in Pre-Health Sciences Pathway to Advanced Diplomas and Degrees",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "19756.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 453,
        "name": "Certificate in Construction Techniques",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "21327.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 454,
        "name": "Certificate in Media Fundamentals",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "19988.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 455,
        "name": "Certificate in Electrical Techniques",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20329.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 456,
        "name": "Certificate in CNC & Precision Machining, Mechanical Techniques",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20587.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      },
      {
        "id": 457,
        "name": "Certificate in Animal Care",
        "level": "diplomas",
        "duration": "1 year",
        "qualification_level": "",
        "tuition": "20118.00",
        "intake": "",
        "note": "",
        "scholarship": ""
      }
    ]
  },
  {
    "id": 16,
    "slug": "cimt-college",
    "name": "CIMT College",
    "country": "Canada",
    "location": "Ontario, Canada",
    "tagline": "Short diploma programmes for international students, under six months and without a practicum",
    "badge": "Partner College",
    "currency": "CAD",
    "application_fee_currency": "NGN",
    "application_fee": "200000.00",
    "application_fee_ngn": "200000.00",
    "is_fee_free": false,
    "tuition_deposit_percent": "0.00",
    "tuition_deposit_amount": "500.00",
    "deposit_note": "CAD 500 tuition deposit",
    "tuition_summary": "Short programmes, tuition on request",
    "features": [],
    "programs": [
      {
        "id": 458,
        "name": "Artificial Intelligence",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 459,
        "name": "Business Administration",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 460,
        "name": "Cabinetry and Furniture Technician",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 461,
        "name": "Data Science and Big Data",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 462,
        "name": "Deep Learning",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 463,
        "name": "Dental Office Administration",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 464,
        "name": "Legal Office Administration",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 465,
        "name": "Machine Learning",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      },
      {
        "id": 466,
        "name": "Medical Office Administration",
        "level": "diplomas",
        "duration": "Under 6 months",
        "qualification_level": "",
        "tuition": null,
        "intake": "",
        "note": "Short diploma programme, no practicum",
        "scholarship": ""
      }
    ]
  }
];

export function getLocalInstitutions(countryName) {
  if (!countryName) return [];
  const q = countryName.trim().toLowerCase();
  return DEFAULT_CATALOG.filter(
    (inst) => (inst.country || '').trim().toLowerCase() === q
  );
}
